#!/usr/bin/env bash
set -oue pipefail

for func in lib/*; do
    if [[ -f "$func" ]]; then
        source "$func"
    fi
done


case "$1" in
    unused)
        get_unused_packages 
        ;;
    prune)
        prune_unused_packages
        ;;
    materialize)
        generate_deployment "$2"
        ;;
    relabel)
        relabel_deployment "$2"
        ;;
    gen_boot)
        booty_bits "$2"
        ;;
    label_boot)
        relabel_boot
        ;;
    pull)
        pull_image "$3"
        ;;
    update)
        update_store "$3" "$2"
        ;;
    itemize)
        populate_store
        create_custom_content_pkg
        ;;
    exch)
        swap_dep
        ;;
    clear)
        clear_staging
        ;;
    *)
        echo default
        ;;
esac

