#!/usr/bin/env bash
set -oue pipefail

deployment="$1"

read -ra pkg_list <<< "$(cat ./.pkgs"$deployment" | tr "\n" " ")"

for package in "${pkg_list[@]}"; do
    printf "Installing package $package...\n"
    rsync -aHlx --link-dest="../../../home/tom/Dokumente/ald2/.store/$package" /home/tom/Dokumente/ald2/.store/$package/ /var/deployments/"$deployment"/ 2>/dev/null || :
done

mkdir -p /var/deployments/"$deployment"/usr/local
rm /var/deployments/"$deployment"/etc/resolv.conf
ln -sf /run/systemd/resolve/stub-resolv.conf /var/deployments/"$deployment"/etc/resolv.conf
