#!/usr/bin/env bash

booty_bits() {
    deployment="$1"

    new_kernel="$(find "/.mat/.store/surface/$deployment/usr/lib/modules" -name vmlinuz -type f)"
    iprint "Installing kernel %s\n" "$new_kernel"
    new_init="$(find "/.mat/.store/surface/$deployment/usr/lib/modules" -name initramfs.img -type f)"
    iprint "Installing initramfs %s\n" "$new_init"

    mkdir -p "/boot/$deployment"
    cp -fa "$new_kernel" "/boot/$deployment" || :
    cp -fa "$new_init" "/boot/$deployment" || :

    cp -fa /.mat/.boot.conf "$deployment.conf"

    sed -i "s@INSERT_DEPLOYMENT@$deployment@g" "$deployment.conf"
    
    mv "$deployment.conf" "/boot/loader/entries/$deployment.conf"
}

relabel_boot() {
    restorecon -RF /boot
}
