#!/usr/bin/env bash
set -oue pipefail

pull_image() {
    SOURCE_IMAGE="$1"

    installed_image="$(podman inspect --format '{{.Digest}}' "$SOURCE_IMAGE")"
    remote_image="$(skopeo inspect --format '{{.Digest}}' "docker://$SOURCE_IMAGE")"

    if [[ "$installed_image" == "$remote_image" ]]; then
        printf "Latest image already pulled.\n"
        exit 0
    else
        podman pull "$SOURCE_IMAGE"
    fi
}

update_store() {
    if [[ -f /.mat/.current && "$(cat /.mat/.current)" != "" ]]; then
        failed="$(cat /.mat/.current)"
        printf "Cleaning up $failed...\n"
        rm -rf "/.mat/.store/${failed:?}"
        echo "" > ./.current
    fi

    SOURCE_IMAGE="$1"
    deployment="$2"

    podman create --name mat-tmp "$SOURCE_IMAGE"
    CMOUNT="$(podman mount mat-tmp)"

    cp -fa "$CMOUNT/.mat/.pkgs" "/.mat/.pkgs$deployment"
    read -ra pkg_list <<< "$(cat /.mat/.pkgs"$deployment" | tr "\n" " ")"

    for package in "${pkg_list[@]}"; do
        if [[ ! -d "/.mat/.store/$package" ]]; then
            printf "Storing package $package...\n"
            echo "$package" > /.mat/.current
            rsync -aHlx "$CMOUNT/.mat/.store/$package" /.mat/.store/ 2>/dev/null || :
            echo "" > /.mat/.current
        fi
    done

    podman unmount mat-tmp
    podman rm mat-tmp
}
