#!/usr/bin/env bash
set -oue pipefail

pull_image() {
    SOURCE_IMAGE="$1"

    installed_image="$(podman inspect --format '{{.Digest}}' "$SOURCE_IMAGE")"
    remote_image="$(skopeo inspect --format '{{.Digest}}' "docker://$SOURCE_IMAGE")"

    if [[ "$installed_image" == "$remote_image" ]]; then
        printf "Latest image already pulled.\n"
        exit 0
    else
        podman pull "$SOURCE_IMAGE"
    fi
}

update_store() {
    if [[ -f .current && "$(cat .current)" != "" ]]; then
        printf "Cleaning up failed packages...\n"
        cat .current | xargs -I{} -P"$(("$(nproc --all)"/2))" \
            rm -rf .store/{}
        echo "" > .current
    fi

    if [[ ! -d .store ]]; then
        mkdir .store
    fi

    SOURCE_IMAGE="$1"
    deployment="$2"

    podman create --name mat-tmp "$SOURCE_IMAGE"
    CMOUNT="$(podman mount mat-tmp)"

    cp -fa "$CMOUNT/.mat/pkgs" "pkgs$deployment"

    install_package() {
        package="$1"
        if [[ ! -d ".store/$package" ]]; then
            printf "Storing package $package...\n"
            rsync -aHlx "$CMOUNT/.mat/.store/$package" .store/ || :
        fi
    }

    export -f install_package
    export CMOUNT

    cat "pkgs$deployment" | xargs -n1 -P"$(("$(nproc --all)"**2))" \
        bash -c 'install_package "$@"' _

    unset -f install_package
    unset CMOUNT

    podman unmount mat-tmp
    podman rm mat-tmp
}
