#!/usr/bin/env bash
set -oue pipefail

get_unused_packages() {
    read -ra pkg_files <<< "$(find . -maxdepth 1 -type f -name ".pkgs*" | tr "\n" " ")"

    depl_pkgs="$(cat "${pkg_files[@]}" | sort -u)"
    store_pkgs="$(find .store -maxdepth 1 -type d ! -path ".store" | cut -d/ -f2 | sort)"

    echo -e "$depl_pkgs\n$store_pkgs" | sort | uniq -u | grep -v "filesystem-.*"
}

prune_unused_packages() {
    read -ra unused_packages <<< "$(get_unused_packages | tr "\n" " ")"
    for pkg in "${unused_packages[@]}"; do
        printf "Pruning $pkg...\n"
        echo "$pkg" > ./.current
        rm -rf ".store/$pkg"
        echo "" > ./.current
    done
}
