#!/usr/bin/env bash

get_unused_packages() {
    read -ra files <<< "$(find /.mat -maxdepth 1 -type f -name ".[0-9]*" | sed -z "s/^.\///")"

    depl_pkgs="$(cat "${files[@]}" | tr -s " " | cut -z -d" " -f1 | tr "\0" "\n")"
    store_pkgs="$(find /.mat/.store/deep -maxdepth 1 ! -type d | cut -d/ -f3)"

    comm -13 <(sort -u <<< "$depl_pkgs") <(sort <<< "$store_pkgs")
}

prune_unused_packages() {
    lock_image_storage u

    prune_path() {
        path="$1"

        printf "Pruning $path...\n"
        rm -rf "/.mat/.store/deep/$path"
    }

    prune_paths() {
        xargs -n1 -P"$(("$(nproc --all)"/2))" bash -c 'prune_path "$@"' _ <<< "$@"
    }

    export -f prune_path
    export -f prune_paths

    get_unused_packages | xargs -n"$(("$(nproc --all)"*2))" -P"$(("$(nproc --all)"/2))" \
        bash -c 'prune_paths "$@"' _

    unset -f prune_path
    unset -f prune_paths

    lock_image_storage l
}
