#!/usr/bin/env bash

set -e

populate_store() {
    store_path() {
        file_path="$1"
        if file_hash="$(cksum -a blake2b --untagged "$file_path" 2>/dev/null)"; then
            test -L "$file_path" && file_hash="l$file_hash"

            # if [[ ! -f ".store/deep/${file_hash%% *}" ]]; then
            #     link "$file_path" ".store/deep/${file_hash%% *}" 2>/dev/null ||
            #         cp -fax --update=none "$file_path" ".store/deep/${file_hash%% *}" 2>/dev/null || :
            # fi
            printf "$file_hash\0" >> files
        fi
    }

    export -f store_path

    printf "Storing files by hash...\n"
    printf "" > files
    find /{usr,etc} ! -type d -print0 | shuf -z | xargs -0 -n1 -P"$(("$(nproc --all)"**2))" \
        bash -c 'store_path "$@"' _

    unset -f store_path
}
