#!/usr/bin/env bash
set -oue pipefail

generate_deployment() {
    deployment="$1"

    read -ra pkg_list <<< "$(cat /.mat/.pkgs"$deployment" | tr "\n" " ")"

    for package in "${pkg_list[@]}"; do
        printf "Installing package $package...\n"
        rsync -aHlx --link-dest="../.store/$package" /.mat/.store/$package/ /.mat/staging/ 2>/dev/null || :
    done

    mkdir -p /.mat/staging/usr/local
    cp -rfa /etc /.mat/staging || :
    rm /.mat/staging/etc/resolv.conf
    ln -sf /run/systemd/resolve/stub-resolv.conf /.mat/staging/etc/resolv.conf
}

relabel_deployment() {
    printf "Relabeling staging tree for SELinux...\nThis might take a minute...\n"
    setfiles -r "/.mat/staging" "/.mat/staging/etc/selinux/targeted/contexts/files/file_contexts" "/.mat/staging" &>/dev/null
}
