#!/usr/bin/env bash

generate_deployment() {
    deployment="$1"

    lock_image_storage u

    install_path() {
        ts="${1##* }" && [[ ! "${ts:0:1}" == "/" ]] && return
        [[ ! -d "/.mat/.store/surface/$deployment$(dirname "${1##* }")" ]]  && 
            mkdir -p "/.mat/.store/surface/$deployment$(dirname "${1##* }")"
        link "/.mat/.store/deep/${1%% *}" "/.mat/.store/surface/$deployment${1##* }" 2>/dev/null || :
    }

    export -f install_path
    export deployment

    printf "Installing deployment...\n"
    cat "/.mat/.$deployment" | xargs -0 -n1 -P"$(("$(nproc --all)"**2))" \
        bash -c 'install_path "$@"' _

    unset -f install_path

    mkdir -p "/.mat/.store/surface/$deployment/usr/local"
    cp -rfa "/etc" "/.mat/.store/surface/$deployment" || :
    rm "/.mat/.store/surface/$deployment/etc/resolv.conf"
    ln -sf "/run/systemd/resolve/stub-resolv.conf" \
        "/.mat/.store/surface/$deployment/etc/resolv.conf" || :

    echo "$deployment" > "/.mat/.store/surface/$deployment/usr/.mat_dep"
    echo "$deployment" > "/.mat/.store/surface/$deployment/usr/.ald_dep"

    lock_image_storage l
}

relabel_store() {
    deployment="$1"

    lock_image_storage u

    printf "Relabeling deployment %s packages...\n" "$deployment"

    find "/.mat/.store/surface/$deployment" -mindepth 2 -maxdepth 2 -print0 | sort -zr | \
        xargs -0 -I{} -P"$(("$(nproc --all)"/2))" setfiles -r "/.mat/.store/surface/$deployment" \
        "/.mat/.store/surface/$deployment/etc/selinux/targeted/contexts/files/file_contexts" {} &>/dev/null

    chcon -t usr_t "/.mat/.store/surface/$deployment/usr" &>/dev/null
    chcon -t etc_t "/.mat/.store/surface/$deployment/etc" &>/dev/null

    lock_image_storage l
}
