#!/usr/bin/env bash

swap_dep() {
    deployment="$1"
    current="$(cat "$PREFIX/usr/.mat_dep")"
    current="${current:-0}"

    if [[ ! -d "$PREFIX/.mat/.store/surface/$deployment" ]]; then
        iprint "No staging deployment!" && exit 1
    fi

    lock_image_storage u
    lock_root_dir u
    lock_usr u
    
    exch "$PREFIX/usr" "$PREFIX/.mat/.store/surface/$deployment/usr"
    exch "$PREFIX/etc" "$PREFIX/.mat/.store/surface/$deployment/etc"

    mv "$PREFIX/.mat/.store/surface/$deployment" "$PREFIX/.mat/.store/surface/$current"

    lock_usr l
    lock_root_dir l
    lock_image_storage l
    mount -o bind,rw "$PREFIX/usr/local" "$PREFIX/usr/local"
}
